use anyhow::Result;

pub fn run() -> Result<()> {
    // Print a shell function that wraps the ez binary.
    // The function intercepts `ez worktree create` and `ez worktree delete` to auto-cd.
    // All other commands pass through to the binary unchanged.
    print!(
        r#"# ez shell integration — generated by `ez shell-init`
# Add to your .bashrc/.zshrc:  eval "$(ez shell-init)"

ez() {{
    if [ "$1" = "worktree" ] && {{ [ "$2" = "create" ] || [ "$2" = "delete" ]; }}; then
        local _ez_path
        _ez_path=$(command ez "$@")
        local _ez_exit=$?
        if [ $_ez_exit -eq 0 ] && [ -n "$_ez_path" ] && [ -d "$_ez_path" ]; then
            cd "$_ez_path" || true
        fi
        return $_ez_exit
    fi
    command ez "$@"
}}
"#
    );
    Ok(())
}
